title: Gustavo Salibi
subtitle: Developer
description: >- # this means to ignore newlines until "baseurl:"
  Gustavo Salibi's personal web page and blog.

url: "https://salibi.dev" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: About Me
    url: /about
  - text: Blog
    url: /blog
  - text: Contact Me
    url: /contact

# Edit these details

author_logo: profile.png
author: Gustavo  Salibi
author_bio: My full name is Gustavo Henrique Storti Salibi (I know, it's a long name). I am currently a student of computer science at the <a href="https://www.unicamp.br/unicamp/english" target="_blank">University of Campinas (Unicamp)</a> and intern at the <a href="https://developeracademy.eldorado.org.br/campinas/" target="_blank">Apple Developer Academy</a>.
#author_email: "gustavo.salibi@gmail.com"
author_location: Brazil
#author_website_url: "http://gsalibi.github.io"
typewrite-text: print(\"Let's develop it!\")

author_work_experiences:
  - company_name: Apple Developer Academy (Feb 2019 - Present)
    company_logo: developer_academy.png
    company_url: developeracademy.eldorado.org.br/campinas
    designation: Internship
    description: Developed 6 complete projects for iOS by research with the target audience, designing the system and programming. Also developed other smaller projects. Use of agile methodologies.
    visibility: true
  - company_name: IBM/Unicamp (Jul 2018 - Sep 2019)
    company_logo: ibm.png
    company_url: openpower.ic.unicamp.br
    designation: Scientific Initiation
    description: Research and development in open source projects involving computational cloud and continuous validation. Ported more than 10 open source projects for Power architecture by working individually on our own Power cloud or together with the communities.
    visibility: true
  - company_name: Unicamp/CEL (Mar 2016 - Jul 2018)
    company_logo: unicamp.jpg
    company_url: www.cel.unicamp.br
    designation: IT Technical Support
    description: Technical support for professors and students. Bash shell script development to automate everyday tasks. Maintenance and administration of the network and machines. Website maintenance with Joomla/PHP technology. Teamwork with interns.
    visibility: true

author_education_details:
  - college_logo: unicamp.jpg
    college_name: Bachelor of Computer Science
    college_url: www.unicamp.br
    college_degree: University of Campinas
    description:  2016 - 2021
    visibility: true

author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
    visibility: true

# social links
#twitter_username: gsalibi
github_username: gsalibi
#facebook_username: gsalibi
linkedin_username: GustavoSalibi
#behance_username: gsalibi
#instagram_username: gsalibi
#medium_username: gsalibi
telegram_username: gsalibi
#dribbble_username: gsalibi
#flickr_username: gsalibi

#for comments
hyvor_talk_website_id: 740

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# formspree (contact form)
formspree_email: gustavo.salibi@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# algolia search
algolia:
  application_id: A8PDDGBHUR
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: "article"
  search_only_api_key: 6d39c09cd3edae02fd86db8848103c96

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
